name: linting-python-code

on: push

jobs:
  python-linting-code:
    runs-on: ubuntu-latest

    steps:
      - name: Super-Linter
        uses: https://github.com/marketplace/actions/super-linter@v5.7.2
